/**
 * Every user-facing string (UX section 9), keyed like the UX copy tables so QA and localisation can map them 1:1. Exact
 * characters matter: ' " " ..., - ². `{name}` / `{user}` arrive already truncated where the surface is constrained
 * (section 9.14); components wrap them in `<bdi>`.
 */
import { formatArea, formatCountdown, formatPerimeter } from '../lib/format';

const pluralPoints = (n: number): string => (n === 1 ? '1 point' : `${n} points`);
const pluralAreas = (n: number): string => (n === 1 ? '1 area' : `${n} areas`);

export const base = {
  auth: {
    tagline: 'Draw and measure areas on the map, together, in real time.',
    signInTitle: 'Sign in to Snapland',
    signUpTitle: 'Create your account',
    username: 'Username or email',
    displayName: 'Display name (optional)',
    displayNameHint:
      'Shown to others on the map. Any language, up to 64 characters. Leave empty to use your username.',
    displayNameTooLong: 'Use up to 64 characters.',
    displayNameInvalid: 'This name can’t be used. Try another.',
    password: 'Password',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    usernameHint: 'Your email, or 3–32 letters, numbers, dots, dashes or underscores.',
    passwordHint: '8 to 128 characters.',
    passwordTooLong: 'Use at most 128 characters.',
    signIn: 'Sign in',
    signingIn: 'Signing in…',
    signUp: 'Create account',
    signingUp: 'Creating account…',
    toSignUp: 'New to Snapland? Create an account',
    toSignIn: 'Already have an account? Sign in',
    usernameRequired: 'Enter your username.',
    passwordRequired: 'Enter your password.',
    badCredentials: 'Username or password is incorrect.',
    usernameTaken: 'That username is already taken. Try another.',
    usernameInvalid: 'Enter an email address, or use 3–32 letters, numbers, dots, dashes or underscores.',
    passwordTooShort: 'Use at least 8 characters.',
    tooManyAttempts: (wait: string) => `Too many attempts. Try again in ${wait}.`,
    tryAgainIn: (wait: string) => `Try again in ${wait}`,
    accountDisabled: 'This account is disabled. Contact your administrator.',
    networkError: 'Can’t reach Snapland. Check your connection and try again.',
    serverError: 'Something went wrong on our side. Try again in a moment.',
    signedOut: 'You’re signed out.',
    retry: 'Retry',
  },
  menu: {
    shortcuts: 'Keyboard shortcuts',
    quietMode: 'Quiet mode',
    quietModeHelp: 'Hide collaborator notifications. You’ll still see their changes on the map.',
    signOut: 'Sign out',
    undoLast: 'Undo last action',
    label: 'Menu',
    labelQuiet: 'Menu, quiet mode on',
    theme: 'Theme',
    themeDark: 'Dark',
    themeLight: 'Light',
  },
  theme: {
    switchedDark: 'Dark theme on',
    switchedLight: 'Light theme on',
  },
  quiet: { chip: 'Quiet mode' },
  // -- v2 Studio chrome (UX section 9.15) ----------------------------------------------------------
  rail: {
    label: 'Tools',
    /** The key part is left out while single-key shortcuts are off. */
    tooltip: (label: string, key: string | null) => (key === null ? label : `${label} · ${key}`),
    areas: 'Areas in view',
    people: 'People',
    shortcuts: 'Keyboard shortcuts',
    editShapeUnavailable: 'Select an area to edit its shape.',
  },
  optbar: {
    /** Browse has no mode tag; the bar still needs a group name. */
    label: 'Options',
    tagDraw: 'Draw area',
    tagSelected: 'Area selected',
    tagPreview: 'History preview',
    loadingDetail: 'Loading full detail…',
  },
  inspector: {
    label: 'Side panel',
    selection: 'Selection',
    selectedArea: 'Selected area',
    history: 'History',
    people: 'People',
    activity: 'Activity',
    selectionEmpty: 'No area selected. Select one on the map or in Areas in view.',
    close: 'Close side panel',
    /** Accessible name of a section's disclosure button: its label and count ("History, 3"). */
    sectionName: (label: string, count: number) => `${label}, ${count}`,
  },
  activity: {
    heldNote: 'Toasts held while you draw',
    heldNoteEdit: 'Toasts held while you edit',
    heldHelp:
      'Notifications about others’ changes wait until you finish. The map and this list still update.',
    empty: 'Changes others make in your view will show up here.',
    meta: (area: string, time: string) => `${area} · ${time}`,
  },
  status: {
    label: 'Map status',
    zoom: (zoom: string) => `z ${zoom}`,
  },
  /** Key hints (C-05, C-29): a key chip and its label. `Ctrl` reads `⌘` on macOS. */
  keys: {
    draw: { chip: 'D', label: 'Draw area' },
    areas: { chip: 'A', label: 'Areas in view' },
    layer: { chip: 'L', label: 'Map / Aerial' },
    shortcuts: { chip: '?', label: 'Shortcuts' },
    editShape: { chip: 'E', label: 'Edit shape' },
    editAnyway: { chip: 'E', label: 'Edit anyway' },
    rename: { chip: 'F2', label: 'Rename' },
    history: { chip: 'H', label: 'History' },
    zoomTo: { chip: 'Z', label: 'Zoom to area' },
    deselect: { chip: 'Esc', label: 'Deselect' },
    delete: { chip: 'Del', label: 'Delete' },
    undoPoint: { chip: 'Backspace', label: 'Undo point' },
    finePan: { chip: '⇧ Arrows', label: 'Fine pan' },
    save: { chip: 'Ctrl S', label: 'Save area' },
    backToDrawing: { chip: 'Esc', label: 'Back to drawing' },
    selectPoint: { chip: '] [', label: 'Select point' },
    deletePoint: { chip: 'Del', label: 'Delete point' },
    exitPreview: { chip: 'Esc', label: 'Exit preview' },
  },
  a11y: {
    skipToMap: 'Skip to map',
    mapLabel: 'Map. Arrow keys pan, plus and minus zoom.',
    workspace: 'Map workspace',
    notifications: 'Notifications',
  },
  draw: {
    button: 'Draw area',
    busy: 'Finish or cancel what you’re doing first.',
    hintStart: 'Click the map to place the first point.',
    hintStartTouch: 'Tap the map to place the first point.',
    hintStartKeyboard: 'Move the map with the arrow keys and press Space to place a point.',
    /** v2 `.short` variants: `{Key}` tokens render as key chips (UX section 9.15). */
    hintStartKeyboardShort: '{Arrows} move · {Space} add point',
    needThree: 'Place at least 3 points.',
    hintFinish: 'Double-click, click the first point, or press Enter to finish.',
    hintFinishShort: 'Double-click or {Enter} to finish.',
    hintFinishKeyboardShort: '{Space} add point · {Enter} finish',
    hintFinishTouch: 'Tap the first point or Finish.',
    finishHere: 'Click to finish',
    readoutLabel: 'Area',
    readoutEmpty: '—',
    points: pluralPoints,
    crossing: 'Edges can’t cross. Place the point somewhere else.',
    crossingShort: 'Edges can’t cross here.',
    spike: 'That point doubles back over the last edge. Place it somewhere else.',
    spikeShort: 'That doubles back. Try elsewhere.',
    closingCrosses: 'Can’t finish yet: the closing edge would cross another edge.',
    closingCrossesShort: 'Closing edge would cross.',
    zeroArea: 'The shape has almost no area (under 1 m²). Move a point to make a shape.',
    zeroAreaShort: 'Almost no area. Move a point.',
    tooLarge: (max: string) => `Too large. Areas can be up to ${max}.`,
    tooLargeShort: (max: string) => `Too large (max ${max}).`,
    extentTooLarge: (maxDeg: number) =>
      `Too wide. An area can span at most ${maxDeg}° across. Undo a point to continue.`,
    extentTooLargeShort: (maxDeg: number) => `Too wide (max ${maxDeg}°).`,
    antimeridian: 'Areas can’t cross the 180° meridian. Place the point on this side.',
    antimeridianShort: 'Can’t cross the 180° line.',
    outOfRange: 'Points can’t go beyond the edge of the map.',
    outOfRangeShort: 'Beyond the map edge.',
    maxPoints: (max: number) => `You’ve reached the ${max}-point limit. Finish the shape or undo a point.`,
    maxPointsShort: (max: number) => `Point limit reached (${max}).`,
    undoPoint: 'Undo point',
    undoPointLabel: 'Undo last point',
    /** The options bar's *Undo point* description (its name is the visible label, WCAG 2.5.3). */
    undoPointHelp: 'Removes the last point.',
    cancel: 'Cancel',
    finish: 'Finish',
    undo: 'Undo',
    finishDisabled: (reason: string) => `Finish is available once the shape is valid: ${reason}`,
    readoutTooltip: (hectares: string, exact: string, perimeter: string) =>
      `${hectares} · ${exact} · perimeter ${perimeter}`,
  },
  save: {
    title: 'Save area',
    name: 'Name',
    namePlaceholder: 'e.g. North Field',
    description: 'Description',
    optional: '(optional)',
    area: 'Area',
    submit: 'Save area',
    saving: 'Saving…',
    back: 'Back to drawing',
    discard: 'Discard',
    addDescription: '+ Add description',
    nameRequired: 'Give the area a name.',
    nameTooLong: (max: number) => `Names can be up to ${max} characters.`,
    descriptionTooLong: (max: number) => `Descriptions can be up to ${max} characters.`,
    charCount: (n: number, max: number) => `${n} of ${max} characters`,
    unsavedChip: 'Unsaved',
    savingChip: 'Saving…',
    serverInvalid: (reason: string) => `This shape can’t be saved: ${reason}. Go back to drawing to fix it.`,
    reason: {
      SELF_INTERSECTION: 'edges cross near the marked point',
      TOO_FEW_POSITIONS: 'it needs at least 3 points',
      TOO_MANY_VERTICES: 'it has too many points',
      AREA_TOO_LARGE: 'it’s larger than 100,000 km²',
      AREA_TOO_SMALL: 'it has almost no area',
      EXTENT_TOO_LARGE: 'it’s wider than 20°',
      ANTIMERIDIAN_CROSSING: 'it crosses the 180° meridian',
      COORDINATE_OUT_OF_RANGE: 'it goes beyond the edge of the map',
      generic: 'the shape isn’t valid',
    } as Readonly<Record<string, string>>,
  },
  edit: {
    button: 'Edit shape',
    buttonLocked: 'Edit anyway',
    title: (name: string) => `Editing “${name}”`,
    hint: 'Drag points to reshape. Drag or click a small midpoint to add a point.',
    hintShort: 'Drag points. Click a midpoint to add.',
    hintTouch: 'Drag points. Tap a midpoint to add one.',
    readoutDelta: (old: string) => `(was ${old})`,
    loadingDetail: 'Loading full detail…',
    holesDisabled: 'This area has holes and can’t be reshaped here.',
    revertedCrossing: 'That move would make edges cross, so the point went back.',
    revertedCrossingShort: 'Edges would cross. Point went back.',
    tooLarge: 'That would make the area larger than 100,000 km², so the point went back.',
    tooLargeShort: 'Too large. Point went back.',
    minPoints: 'An area needs at least 3 points.',
    deleteWouldCross: 'Removing this point would make edges cross.',
    deleteWouldCrossShort: 'Removing it would cross edges.',
    deletePoint: 'Delete point',
    movePoint: 'Move point',
    movePointArmed: 'Click where the point should go. Esc to stop.',
    movePointArmedTouch: 'Tap where the point should go.',
    stopMove: 'Stop',
    save: 'Save changes',
    saveShort: 'Save',
    saving: 'Saving…',
    cancel: 'Cancel',
    undo: 'Undo',
    serverInvalid: (reason: string) =>
      `These changes can’t be saved: ${reason}. Adjust the shape and try again.`,
    serverInvalidShort: 'This shape can’t be saved. Adjust it.',
    newerVersion: (user: string, n: number) =>
      `${user} saved a newer version (v${n}) while you were editing. When you save, we’ll combine your changes or ask you to choose.`,
    newerVersionShort: (user: string) => `${user} saved a newer version.`,
    otherEditing: (user: string) =>
      `${user} is also editing this area. The second save may need a quick review.`,
    otherEditingShort: (user: string) => `${user} is also editing this.`,
    review: 'Review',
    pointSelected: (i: number, n: number) => `Point ${i} of ${n} selected.`,
  },
  panel: {
    createdBy: (user: string, date: string) => `Created by ${user} · ${date}`,
    editedBy: (user: string, time: string) => `Last edited by ${user} · ${time}`,
    version: (n: number) => `Version ${n}`,
    metrics: (perimeter: string, n: number) => `Perimeter ${perimeter} · ${pluralPoints(n)}`,
    noDescription: 'No description.',
    zoomTo: 'Zoom to area',
    delete: 'Delete',
    close: 'Close area details',
    deletedByOther: (user: string, time: string) => `${user} deleted this area ${time}.`,
    restoreArea: 'Restore area',
    askToRestore: (user: string) => `Ask ${user} or an admin to restore it.`,
    saveCopy: 'Save a copy as a new area',
    copyName: (name: string) => `Copy of ${name}`,
    closeButton: 'Close',
    rename: 'Rename',
    renameLabel: (name: string) => `Rename ${name}`,
    description: 'Description',
    descriptionAdd: 'Add description',
    descriptionEdit: 'Edit',
    descriptionSave: 'Save',
    descriptionCancel: 'Cancel',
    unsavedName: (text: string) => `Your unsaved text: “${text}”`,
  },
  perm: {
    deleteOwnerOnly: (creator: string) => `Only ${creator} or an admin can delete this area.`,
    deleteOwnerOnlyGeneric: 'Only the person who created this area or an admin can delete it.',
  },
  summary: {
    // An empty view has no total to show ("< 1 m²" would claim a tiny area).
    inView: (n: number, total: string) =>
      n === 0 ? `${pluralAreas(0)} in view` : `${pluralAreas(n)} · ${total} in view`,
    help: 'Sum of the areas shown. Overlapping areas are each counted; very small areas hidden at this zoom are not included.',
  },
  list: {
    title: (n: number) => `Areas in view (${n})`,
    heading: 'Areas in view',
    sort: 'Sort by',
    sortRecent: 'Recently edited',
    sortName: 'Name',
    sortSize: 'Size',
    empty: 'No areas in this view. Pan or zoom out, or draw a new one.',
    back: 'Back to list',
    filter: 'Filter by name',
    filterEmpty: (q: string) => `No areas in view match “${q}”.`,
    capped: (cap: number, n: string) => `Showing ${cap} of ${n} loaded. Zoom in or filter by name.`,
    culled: (n: string) => `${n} small areas aren’t listed at this zoom.`,
    edited: (time: string, user: string) => `edited ${time} by ${user}`,
    close: 'Close areas list',
  },
  history: {
    loading: 'Loading history…',
    loadError: 'Couldn’t load history.',
    current: 'Current',
    created: (area: string) => `Created · ${area}`,
    reshaped: (old: string, next: string) => `Reshaped · ${old} → ${next}`,
    renamed: (old: string) => `Renamed from “${old}”`,
    described: 'Description edited',
    multi: 'Reshaped and renamed',
    updated: 'Edited',
    deleted: 'Deleted',
    undeleted: 'Restored after delete',
    restoredFrom: (m: number) => `Restored from v${m}`,
    merged: ' (merged)',
    previewBanner: (n: number, time: string) => `Previewing v${n} from ${time}.`,
    previewTag: 'Preview',
    legendGhost: (n: number, date: string) => `v${n} · ${date}`,
    legendCurrent: (n: number) => `Current v${n}`,
    restore: 'Restore this version',
    restoring: 'Restoring…',
    restoreDisabledCurrent: 'This is the current version.',
    restoreDisabledDeleted: 'This entry records a delete, so there’s nothing to restore from it.',
    exitPreview: 'Exit preview',
    restoreConflict:
      'Someone changed this area while you were looking. History is up to date — choose again.',
  },
  toast: {
    saved: (name: string, area: string) => `Saved “${name}” · ${area}`,
    editSaved: (name: string, n: number) => `Saved changes to “${name}” · v${n}`,
    renamed: (name: string) => `Renamed to “${name}”`,
    deleted: (name: string) => `Deleted “${name}”`,
    undeleted: (name: string) => `“${name}” is back`,
    alreadyRestored: (user: string, name: string) => `${user} already restored “${name}”.`,
    deleteFailed: (name: string) => `Couldn’t delete “${name}”. It’s back on the map.`,
    deleteFailedShort: 'Not deleted. It’s back on the map.',
    deleteConflict: (user: string, name: string) =>
      `${user} just changed “${name}”, so it wasn’t deleted. Check the change, then delete again if you still want to.`,
    deleteConflictShort: (user: string) => `${user} changed it first. Not deleted.`,
    forbiddenDelete: (creator: string, name: string) =>
      `Only ${creator} or an admin can delete “${name}”. It’s back on the map.`,
    forbiddenRestore: (creator: string, name: string) => `Only ${creator} or an admin can restore “${name}”.`,
    areaGone: 'This area no longer exists.',
    drawingDiscarded: 'Drawing discarded',
    changesDiscarded: (name: string) => `Changes to “${name}” discarded`,
    restoredVersion: (old: number, name: string, next: number) => `Restored v${old} of “${name}” as v${next}`,
    restoreNoop: (name: string, old: number) => `“${name}” already matches v${old}. Nothing changed.`,
    tookTheirs: (user: string) => `Your changes were discarded. You’re now seeing ${user}’s version.`,
    tookTheirsShort: (user: string) => `Showing ${user}’s version. Undo to get yours.`,
    autoMerged: (user: string, name: string, theirs: string, mine: string, n: number) =>
      `${user} also edited “${name}”. Their ${theirs} and your ${mine} were both saved (v${n}).`,
    autoMergedUnknown: (name: string, theirs: string, mine: string, n: number) =>
      `Someone also edited “${name}”. Their ${theirs} and your ${mine} were both saved (v${n}).`,
    saveFailedNetwork: (name: string) =>
      `Couldn’t save “${name}”. Check your connection — your work is kept.`,
    saveFailedNetworkShort: 'Not saved: no connection. Work is kept.',
    saveFailedServer: 'Something went wrong on our side while saving. Your work is kept.',
    saveFailedServerShort: 'Not saved: a problem on our side. Work kept.',
    saveTimeout: (name: string) => `Saving “${name}” is taking too long. Your work is kept.`,
    saveTimeoutShort: 'Saving timed out. Your work is kept.',
    storageUnavailable: 'Saving is delayed by a problem on our side. Retrying…',
    backOnline: (n: number) =>
      `You’re back online. ${n} ${n === 1 ? 'area' : 'areas'} in view changed while you were away.`,
    backOnlineNoChanges: 'You’re back online.',
    undo: 'Undo',
    retry: 'Retry',
    show: 'Show',
    dismiss: 'Dismiss',
    fieldNames: { geometry: 'shape change', name: 'name change', description: 'description change' } as const,
  },
  collab: {
    created: (user: string, name: string, area: string) => `${user} created “${name}” · ${area}`,
    reshaped: (user: string, name: string, area: string) => `${user} reshaped “${name}” · ${area}`,
    renamed: (user: string, old: string, name: string) => `${user} renamed “${old}” to “${name}”`,
    described: (user: string, name: string) => `${user} edited the description of “${name}”`,
    updated: (user: string, name: string) => `${user} updated “${name}”`,
    deleted: (user: string, name: string) => `${user} deleted “${name}”`,
    undeleted: (user: string, name: string) => `${user} restored “${name}”`,
    restoredVersion: (user: string, m: number, name: string) => `${user} restored v${m} of “${name}”`,
    summary: (n: number, users: string) => `${n} changes by ${users}`,
    heldSummary: (n: number, users: string) => `While you worked: ${n} changes by ${users}`,
    draftChip: (user: string) => `${user} · drawing`,
    draftChipArea: (user: string, area: string) => `${user} · drawing · ${area}`,
    editChip: (user: string) => `${user} · editing`,
    draftIdle: (user: string) => `${user} · paused`,
    updatedChip: (user: string) => `${user} · updated`,
    someone: 'Someone',
  },
  lock: {
    badge: (user: string) => `${user} is editing`,
    chipBoth: (user: string) => `${user} is editing too`,
    bannerTitle: (user: string) => `${user} is editing this area.`,
    bannerBody: 'You can still edit. If you both save, the second save may need a quick review.',
    editAnywayHint: (user: string) => `${user} is editing this area. Press Enter on Edit anyway to edit too.`,
    hudBoth: (user: string) => `${user} is editing this area too.`,
    hudBothShort: (user: string) => `${user} is editing this too.`,
    heldRace: (user: string) =>
      `${user} just started editing this area. You can continue; the second save may need a quick review.`,
    heldRaceShort: (user: string) => `${user} just started editing this.`,
    unknown: 'We can’t check right now whether someone else is editing this area.',
    unknownShort: 'Can’t check who else is editing.',
  },
  presence: {
    header: 'On the map now',
    count: (n: number) => `${n} on the map`,
    you: 'You',
    viewing: 'Viewing',
    drawing: 'Drawing a new area',
    editing: (name: string) => `Editing “${name}”`,
    editingUnknown: 'Editing an area',
    idle: 'Idle',
    onlyYou: 'Only you are here right now.',
    /** The People header's trailing note while the live channel is up (UI.md section 10.8.6). */
    liveNote: 'online',
    limited: 'People list refreshes every 15 seconds while live updates are paused.',
    unavailable: 'Who’s here is unavailable while you’re offline.',
    changesCounter: (n: number) => `${n} changes nearby`,
    /** The desktop button's name starts with its visible text, "{n} online" (WCAG 2.5.3 label in name). */
    button: (n: number) => `${n} online, show who’s on the map`,
    online: (n: number) => `${n} online`,
  },
  conflict: {
    title: (user: string, name: string) => `${user} saved “${name}” while you were editing`,
    body: 'Some of your changes overlap with theirs. Choose what to keep — nothing is lost, every version stays in history.',
    keepMine: 'Keep mine',
    keepMineHelp: (user: string) => `Save your version. ${user}’s changes stay in history.`,
    takeTheirs: 'Take theirs',
    takeTheirsHelp: (user: string) => `Discard your changes and use ${user}’s version. You can undo this.`,
    review: 'Review differences',
    reviewHelp: 'Choose field by field.',
    later: 'Decide later',
    colField: 'Field',
    colYours: 'Yours',
    colTheirs: (user: string, n: number) => `Theirs (${user}, v${n})`,
    fieldShape: 'Shape',
    fieldName: 'Name',
    fieldDescription: 'Description',
    mergedAuto: 'Merged automatically — only one of you changed this.',
    saveMerged: 'Save merged version',
    legendMine: 'Your shape',
    legendTheirs: (user: string) => `${user}’s shape`,
    showMine: 'Show mine',
    showTheirs: 'Show theirs',
    changedAgain: (user: string) =>
      `${user} saved another version meanwhile. Here’s the latest — choose again.`,
  },
  deletedWhileEditing: {
    title: (user: string, name: string) => `${user} deleted “${name}” while you were editing`,
    body: 'Your changes haven’t been saved yet.',
    bodyNoRestore: (creator: string) =>
      `Your changes haven’t been saved yet. Only ${creator} or an admin can restore the area, so you can save your version as a new area.`,
    restore: 'Restore it with my changes',
    saveNew: 'Save as a new area',
    discard: 'Discard my changes',
  },
  conn: {
    connecting: 'Connecting…',
    live: 'Live',
    reconnecting: 'Reconnecting…',
    limited: 'Limited connection',
    offline: 'Offline',
    signedOut: 'Signed out',
    short: {
      connecting: 'Connecting…',
      live: 'Live',
      reconnecting: 'Retrying…',
      limited: 'Limited',
      offline: 'Offline',
      'signed-out': 'Signed out',
    } as const,
    ariaLabel: (full: string) => `Connection: ${full}. Show details`,
    liveDetail: 'You’re connected. Changes from others appear instantly.',
    reconnectingDetail: (s: number) => `Connection lost. Trying again in ${s} s. You can keep working.`,
    limitedDetail: (poll: number) =>
      `Live updates are paused. We check for changes every ${poll} seconds and saving still works.`,
    offlineDetail:
      'You’re offline. Keep drawing — your work stays on this device, and you can save when you’re back online.',
    offlineSaveDisabled: 'You’re offline. Saving will be available when you reconnect.',
    reconnectNow: 'Reconnect now',
  },
  rate: {
    chip: (wait: string) => `Live sharing paused · ${wait}`,
    chipPaused: 'Live sharing paused',
    chipHelp: 'Keep drawing, nothing is lost.',
    sharingPausedSr: (wait: string) =>
      `Live sharing is paused for ${wait} because of the limit of 50 drawing actions a minute. Keep drawing; nothing is lost.`,
    saveButton: (wait: string) => `Saving in ${wait}…`,
    restoreButton: (wait: string) => `Restoring in ${wait}…`,
    renameLine: (wait: string) => `Saving the name in ${wait}…`,
    deleteToast: (name: string, wait: string) => `Deleting “${name}” in ${wait}…`,
    help: 'Limit: 50 drawing actions a minute.',
    cancel: 'Cancel',
  },
  session: {
    title: 'Your session has expired',
    body: 'Sign in again to continue. Your work is safe and will be right where you left it.',
    revokedTitle: 'You were signed out',
    revokedBody:
      'Your session was ended on another device or by an administrator. Sign in again to continue — your work is safe here.',
    submit: 'Sign in and continue',
    switchUser: 'Sign in as someone else',
    signOut: 'Sign out instead',
  },
  signout: {
    title: 'Sign out with unsaved work?',
    body: 'You have an unsaved drawing. If you sign out now, it will be discarded.',
    keep: 'Keep working',
    confirm: 'Discard and sign out',
  },
  restore: {
    drawing: (time: string) => `You have an unsaved drawing from ${time}.`,
    edit: (name: string, time: string) => `You have unsaved changes to “${name}” from ${time}.`,
    restore: 'Restore',
    resume: 'Resume editing',
    discard: 'Discard',
  },
  map: {
    loading: 'Loading areas…',
    emptyTitle: 'No areas here yet.',
    emptyBody: 'Draw one with Draw area (D).',
    truncatedNoTotal: (shown: string) => `Showing the first ${shown} areas. Zoom in to see all.`,
    culled: (n: string) => `${n} small areas are hidden at this zoom. Zoom in to see them.`,
    zoomIn: 'Zoom in',
    loadError: 'Couldn’t load areas for this view.',
    rateLimited: (wait: string) => `Too many requests. Loading again in ${wait}.`,
    storageUnavailable: (wait: string) =>
      `Areas can’t load because of a problem on our side. Retrying in ${wait}.`,
    retry: 'Retry',
    dismiss: 'Dismiss',
  },
  layer: {
    groupLabel: 'Base map',
    map: 'Map',
    aerial: 'Aerial',
    toggleLabel: (layer: string) => `Switch base map to ${layer}`,
    aerialTooltipEsri: 'Aerial photos from Esri World Imagery',
    aerialTooltipItm: 'GovMap aerial photo (2022)',
    switchedMap: 'Map base map on',
    switchedAerial: 'Aerial base map on',
    outsideCoverage: 'Aerial covers Israel only.',
    zoomClamped: 'Zoomed out to the closest level Aerial supports.',
    tilesFailing: (layer: string) => `${layer} tiles aren’t loading right now.`,
    switchTo: (layer: string) => `Switch to ${layer}`,
    attribOsm: '© OpenStreetMap contributors',
    attribEsri: 'Imagery © Esri, Maxar, Earthstar Geographics',
  },
  coord: {
    readout: (lat: string, lng: string, e: string, n: string) => `${lat}, ${lng} · ITM E ${e} N ${n}`,
    centreLabel: 'Map centre:',
    help: 'Pointer position (the map centre when the pointer is off the map), in latitude/longitude and in the Israeli Transverse Mercator grid (ITM, metres).',
  },
  sr: {
    drawMode:
      'Drawing mode. Move the map with the arrow keys, Space places a point, Enter finishes, Escape cancels.',
    editMode: (name: string) =>
      `Editing “${name}”. Brackets select points, arrow keys move the selected point, Enter saves, Escape cancels.`,
    pointAdded: (n: number, area: string) => `Point ${n} added. Area ${area}.`,
    pointRemoved: (n: number, area: string) => `Point removed. ${pluralPoints(n)}. Area ${area}.`,
    pointRefused: (reason: string) => `Can’t place a point there. ${reason}`,
    finishRefused: (reason: string) => `Can’t finish. ${reason}`,
    conflictAlert: 'Save conflict.',
    pointMoved: (area: string) => `Point moved. Area ${area}.`,
    areaUnknown: 'not available yet',
  },
  shortcuts: {
    title: 'Keyboard shortcuts',
    singleKeys: 'Single-key shortcuts',
    singleKeysHelp: 'Letter shortcuts such as D and L. Turn off if they get in your way.',
    close: 'Close',
  },
  common: {
    waitRetry: (wait: string) => `Too many requests. Trying again in ${wait}.`,
    close: 'Close',
    expand: 'Expand',
    collapse: 'Collapse',
  },
} as const;

/** The readout text: "Area 2.31 km²" or "Area - ". */
export function readoutText(km2: number | null): string {
  return km2 === null ? base.draw.readoutEmpty : formatArea(km2);
}

export function wait(ms: number): string {
  return formatCountdown(ms);
}

export function perimeterText(km: number): string {
  return formatPerimeter(km);
}

/** "Dana", "Dana and Omer", "Dana, Omer and 2 others" (UX `collab.summary`). */
export function joinUsers(users: readonly string[]): string {
  const unique = [...new Set(users)];
  if (unique.length <= 1) return unique[0] ?? base.collab.someone;
  if (unique.length === 2) return `${unique[0] ?? ''} and ${unique[1] ?? ''}`;
  if (unique.length === 3) return `${unique[0] ?? ''}, ${unique[1] ?? ''} and ${unique[2] ?? ''}`;
  return `${unique[0] ?? ''}, ${unique[1] ?? ''} and ${unique.length - 2} others`;
}

/** Field names in auto-merge toasts, joined with "and" (UX section 9.7). */
export function fieldList(fields: readonly ('geometry' | 'name' | 'description')[]): string {
  const names = fields.map((field) => base.toast.fieldNames[field]);
  if (names.length <= 1) return names[0] ?? '';
  return `${names.slice(0, -1).join(', ')} and ${names.at(-1) ?? ''}`;
}
